Rails.application.routes.draw do
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/thanks' => 'pages#thanks'
  get '/messages' => 'messages#index'
  get '/messages/new' => 'messages#new'
  post 'messages' => 'messages#create'
  get '/signup', to: 'user#new'
  post '/signup', to: 'user#create'
  post '/images', to: 'user#show'
  get '/image', to: 'user#index'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  
end
